name: flutter_ed448

description: >-
  Flutter-compatible Dart implementations of SHA-3, BLAKE3,
  EdDSA/Ed448, and Ed448 JWT helpers.

version: 0.2.1

environment:
  sdk: '>=3.0.0 <4.0.0'

repository: https://github.com/CorePass/flutter_ed448
homepage: https://github.com/CorePass/flutter_ed448
issue_tracker: https://github.com/CorePass/flutter_ed448/issues
topics:
  - cryptography
  - ed448
  - jwt
  - sha3
  - blake3

dependencies:
  pointycastle: ^4.0.0
dev_dependencies:
  lints: ^6.0.0
  node_preamble: ^2.0.1
  test: ^1.24.0

executables:
  flutter_ed448:
  thirds:
